### ISSUE TITLE
EPIC: Increase code coverage

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#1032]
Task for coordinating increasing code coverage. Packages are listed below, create an issue for the specific package and assign it to yourself when increasing coverage.

See codecov for coverage % of each package: https://app.codecov.io/gh/deephaven/web-client-ui/tree/main/packages

- [ ] Increase code coverage in package chart (do last, package may be deprecated)
- [ ] Increase code coverage in package code-studio
- [x] #1054
- [ ] Increase code coverage in package console
- [x] #1095
- [ ] Increase code coverage in package dashboard-core-plugins
- [x] #1049
- [x] #1148
- [ ] Increase code coverage in package iris-grid
- [ ] Increase code coverage in package jsapi-components
- [x] #1096
- [x] #1089
