### ISSUE TITLE
EPIC: Support a data bar cell render for numeric columns

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1103]
Data bar formatting is an easy way to visualize a numeric columns value relative to other values in that column. See attached spec:
https://drive.google.com/open?id=1D7iI7mi2K7r0EhJ4IKCwDFuBVkuXLE8E (deephaven internal link)

This requires several things:
- [x] deephaven/deephaven-core#3546
- [x] deephaven/deephaven-core#3547
- [x] deephaven/web-client-ui#1151
- [x] deephaven/deephaven-core#3549
- [x] deephaven/web-client-ui#1152

**Comment by niloc132** [comment]
JS API support consists only of https://github.com/deephaven/deephaven-core/issues/3314 - all join types are already present. The theory here is that the UI will create a 1-row totals table with the max/min of each relevant column, then join that against every row of the original table, and read min/max/value within each row to render each bar.

**Comment by emilyhuxng** [comment]
# Parameters
1. column: the column name of the column that will be of databar type
2. data: the column the value is from
3. axis: the position of the axis (default: proportional, middle, directional)
4. min: the minimum value (default: the minimum value of the data column)
5. max: the maximum value (default: the maximum value of the data column)
6. positive_color: the color of positive values (default: theme green). Could be a string or an array of strings for a gradient.
7. negative_color: the color of negative values (default: theme red). Could be a string or an array of strings for a gradient.
8. value_placement: the placement of the value (default: beside, overlap, hide)
9. direction: the direction of the bar (default: LTR, RTL)
10. markers: an array of markers which contain a column name and a color

Example API commands for the examples in the spec:

1. Proportional axis: `table = students.format_databar(column=“MyGauge”, data="GPA")`
11. Axis in cell middle: `table = students.format_databar(column="MyGauge", data="GPA", axis="middle")`
12. No negative axis: `table = students.format_databar(column="MyGauge", data="GPA", axis="directional")`
13. Custom positive and negative color: `table = students.format_databar(column="MyGauge", data="GPA", positive_color="#0000ff", negative_color="#ffff00")`
14. Solid color: `table = students.format_databar(column="MyGauge", data="GPA", positive_color="#ff00ff", negative_color="#ff00ff")` or `table = students.format_databar(column="MyGauge", data="GPA", color="#ff00ff")`
15. Positive and negative gradient: `table = students.format_databar(column="MyGauge", data="GPA", positive_color=["#ffff00", "#00ff00"], negative_color=["#ff0000", "#ffff00"])`
16. Hide values and no negative axis: `table = students.format_databar(column="MyGauge", data="GPA", axis="directional", value_placement="hide")`
17. Overlap values and lowered opacity: `table = students.format_databar(column="MyGauge", data="GPA", axis="directional", value_placement="overlap", opacity=0.5)`
18. Right to left and overlap: `table = students.format_databar(column="MyGauge", data="GPA", value_placement="overlap", opacity=0.5, direction="RTL")`
19. Left to right and overlap: `table = students.format_databar(column="MyGauge", data="GPA", value_placement="overlap", opacity=0.5, direction="LTR", text_alignment="left")`
20. Right to left with no negative: `table = students.format_databar(column="MyGauge", data="GPA", axis="directional" value_placement="beside", direction="RTL")`
21. Default with left alignment: `table = students.format_databar(column=“MyGauge”, data="GPA", text_alignment="left")`
22. Markers: `table = students.format_databar(column=“MyGauge”, data="GPA", markers=["English Mark", "#ffffff"])`

**Comment by dsmmcken** [comment]
Parameters:
2. Thinking about naming, longer but maybe better? `value_column` I don't know if we have a good example to draw on. Open to other ideas.
11. I prefer your example where you just specify as same color, and would drop
12. This would be a separate API, probably part of layout hints, so not necessary here.

Examples:
Missing examples with min/max showing values and auto. 
1. We should assume column and data are the same if data is not specified?
8. If color accepts rgba or #RRGGBBAA then opacity is probably not necessary

**Comment by ethanalvizo** [comment]
Markers won't be possible until this https://github.com/deephaven/deephaven-core/issues/2102 is resolved

**Comment by dsmmcken** [comment]
I don't think that's correct. Markers are just values from a column, not an array.

**Comment by ethanalvizo** [comment]
> I don't think that's correct. Markers are just values from a column, not an array.

I thought markers is being passed in as an array of arrays

<img width="773" alt="image" src="https://github.com/deephaven/web-client-ui/assets/55671206/0782c816-3da5-4b7e-affd-eaa82771e1a0">

**Comment by dsmmcken** [comment]
For defining the markers yes, because one could define multiple markers. The values themselves come from the column with values, not a column of arrays.

**Comment by mofojed** [comment]
The values we'd put in the markers column as well, and the markers within that column are going to be an array. Need to be able to read the full array to get all the values.
We could just encode the whole array as a JSON string though.

**Comment by ethanalvizo** [comment]
Would it be possible on the API side to return the column name that the markers should refer to rather than the values themselves? Then on the web-client side we can look at the value of that column name for that specific row to place the marker. Or is that not possible? This approach would require every row to have a marker though

`{ databar.markers -> "GPA" }`

**Comment by dsmmcken** [comment]
The marker value needs to come from the server. Client should be dumb and not attempt to calculate where the marker should be placed relative to the range.

**Comment by mofojed** [comment]
API support will be added to the `ui.table` functionality of `deephaven.ui`.
