### ISSUE TITLE
EPIC: Plugin Enhancements

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#1435]
There are a number of plugin enhancements we want to make. When talking about plugins, this is the current terminology

- `DashboardPlugin` - Gets mounted to the dashboard. Doesn't necessarily need to display anything on its own unless it floats over the dashboard (Linker). Typically used to listen for widgets from the server and emit panel open events
- `WidgetPlugin` - Plugin that handles displaying a widget from the server. Right now tables, plots, data frames
- `TablePlugin` - A plugin to enhance a table widget. Mounted with the table
- `CompositePlugin` - A plugin that is really a collection of other plugin types to simplify packaging/authoring plugins. More of a "suite" of plugins bundled into 1 package
- `AuthPlugin` - A plugin to implement an authentication strategy

As of writing this ticket, we support `DashboardPlugin`, `AuthPlugin`, and `TablePlugin`.

- [ ] #1167 
- [ ] Change plugins to expect a default exported object (or function if there's anything we think should be available at runtime to the config) containing things like `component`, `supportedTypes`, etc. Add TS types for the different plugin config types
- [ ] Add a `WidgetPlugin`. This is a simplified version of basically everything from the js-plugins repo. The plugin author specifies a component, types supported, an optional icon, and then we register it to listen for panel open events matching the supported types. This should also wrap the component in our panel wrapper
- [ ] Deprecate props (maybe not dashboardId) passed to plugins from `DashboardLayout` clone element call. Any props needed here like `registerComponent` could be in a context. This might help simplify the types around plugin panels (see [here](https://github.com/deephaven/web-client-ui/pull/1409#discussion_r1272929241))
- [ ] Add golden layout event hub and global event hub to a context instead of passing through props (see [here](https://github.com/deephaven/web-client-ui/pull/1409#discussion_r1272970177))
- [ ] Add support for plugin "suites" or composite plugins. Most likely just need to support an array of config objects as an option for plugin configs
- [ ] Add lazy loading support. This would require the manifest to specify what widget types the plugin supports and probably a `defer` prop to indicate it should lazy load
- [ ] Add support for multiple `TablePlugin`s on 1 table
- [ ] Add support for a "global" `TablePlugin` that is applied to tables automatically. These plugins would have a function to allow ignoring tables when they're created (so it could apply to all tables, but ignore tree tables)
