### ISSUE TITLE
EPIC: Theming

### ISSUE THREAD

**Issue by bmingles** [deephaven/web-client-ui#1537]
Support theming in Deephaven. Provide a base light and dark theme, and support custom themes via plugins.

- [x] #1504 - Load default themes. Load custom themes from plugins. Cache info from last selected theme to reload on app start
- [x] Theme Selector Component - Add a theme selector to the settings menu and save to workspace
- [x] #1538 - Base Dark Theme - Create set of base theme variables for dark theme
- [x] #1539 - Base Light Theme - Re-define base set of theme variables for a light theme
- [x] #1531 - Loading spinner should be styled based on theme. It should be styled before app loads.
- [x] #1540 - Bootstrap Variables - Map Bootstrap variables to theme variables
- [x] ??? Components - Update DH components to use theme variables (maybe part of #1540 but TBD)
- [x] #1541 - Update IrisGrid to use theme variables. Requires deriving CSS prop values and converting to .js based theme.
- [x] #1542 - Update Monaco theming to use theme variables. Requires deriving CSS prop values and converting to .js based theme.
- [x] #1543 - Create custom Spectrum theme variables mapped to DH theme variables. Custom Spectrum theme provider component to provide this theme.
- [x] #1544 - Update our current usage of React Spectrum components to use DH theming.
- [x] #1572
- [x] Enterprise theme plugins

**Comment by mofojed** [comment]
@bmingles can this ticket be closed?
