### ISSUE TITLE
EPIC: Improve Documentation

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#445]
Our documentation needs to be beefed up in many areas to encourage usage.

- [ ] Docs for @deephaven/log
- [ ] Docs for @deephaven/grid
- [ ] Docs for @deephaven/iris-grid
- [ ] Docs for @deephaven/components

**Comment by mofojed** [comment]
Documentation push should start in March
