### ISSUE TITLE
EPIC: Column Grouping UI

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#694]
Complete column grouping UI 

- [ ] #620 
- [x] Column grouping display based on layout hints from the API
- [ ] Side panel group management
- [ ] Context menu specific to groups?
- [ ] Resizing groups in the UI/Hide button from spec
- [ ] Make dragging a column outside the canvas scroll at different speeds depending how far outside the column is
