### ISSUE TITLE
EPIC: Linker improvements

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#843]
We have a several improvements to linker that we plan to make:
  
## Linker comparison operators:

The purpose of these improvements is to provide users with more flexibility with creating links. Specifically, the combination of setting a comparison operator per link, with conjunctively combining links from the same source table linked to the same target column, will allow the users to create new powerful linker driven filters, such as their own "range" filter.

Ex. User has Table A with columns: `id`, `start_time`, `end_time`, and Table B with columns: `id` and `timestamp`. By linking `id` to `id`, and `start_time` <= to `timestamp` and  `timestamp` <= `end_time` the user would be able to filter Table B based on a range provided from Table A.

- [x] #887
  - [x] Add new default styling $blue, mix($blue, $content-bg, 25%), hover styling ($primary, $primary-hover), and selected styling is previous default styling as per mockup:
  ![image](https://user-images.githubusercontent.com/1576283/197881574-4389d10b-a070-4353-b0e0-c5115c2371dc.png)
  - [x] Add support for setting filter comparison operator on links
  ![image](https://user-images.githubusercontent.com/1576283/197880900-743bdf83-3bcf-4dca-83e1-ec704b8d513b.png)
  Note: linker colors are incorrect in this mockup, see previous point for updated style
  - [x] Click to delete no longer applies, must now be selected first then deleted. Delete being a two-step operation I don't like as much, so open to suggestions. Maybe at least an alt-click (with delete mode cursor during alt press?)
  - [x] Links originating from multiple source columns in the same table, going to the same target column in target table should be combined. Conjunctively with && and unless one of the source columns is set to an equals operator, in which case use disjunctive || or filter.
  - [x] Comparison operators and their combination should still show correctly in the quick filter bar.

## Other minor ux improvements: 
- [x] #875
- [x] #1035
- [x] When hovering a link, it should be brought to front, so the arrow and ball on each of the link is on top of the hover stack
- [x] #964
  ![image](https://user-images.githubusercontent.com/1576283/207144544-68241871-2f5d-4c47-b7e3-3bd06664a1bc.png)
- [x] #906
- [x] #901
  ![image](https://user-images.githubusercontent.com/1576283/197880089-8310cc91-97a2-449e-ae5e-0a5a92db106a.png)
  Note: allow left edge to act as grab handle, and be moveable anywhere in bounds.

**Comment by devinrsmith** [comment]
Very cool. This seems like a very powerful feature. I'm wondering, is there an even more generic version that can be expressed kind-of like a free-form where filter?

I'm interested in the data model that would underlie this, and how we'd eventually allow programmatic creation of it (@mofojed). I think there might be good reasons to look at `io.deephaven.api.filter.Filter` from the programmatic side with JSON ser/deser.

**Comment by dsmmcken** [comment]
For programmatic, I was thinking we expose the ability to attach a callback to a table double-click handler that receives column values from the row you specified, and gets called server-side. You could then perform whatever filter operations you want in the callback.

**Comment by devinrsmith** [comment]
Using callbacks is an interesting thought, particularly relevant for programmatic filtering or other things that output tables - saves the need to create ser/deser logic.
